#!/usr/bin/env bash
# Displays information about subdomains

display_info () {
    domain=$1
    subdomain=$2
    dig "$subdomain.$domain" A | awk -v subd="$subdomain" '/ANSWER SECTION:/{ getline; printf "The subdomain %s is a %s record and points to %s\n", subd, $4, $5 }'
}

re="^[a-zA-Z]+$"
if [ "$#" -eq 1 ]; then
    # ensure that argument is a string
    if [[ "$1" =~ "$re" ]]; then
        echo "error: not alphabetical"
	exit 3
    fi

    for sub in "www" "lb-01" "web-01" "web-02"
    do
	display_info "$1" "$sub"
    done

elif [ "$#" -eq 2 ]; then
    # ensure that arguments are strings
    if [[ "$2" =~ "$re" ]]; then
        echo "error: not alphabetical"
	exit 3
    fi

    display_info "$1" "$2"
else
    echo "Allowed arguments: <domain> <subdomain>(optional)"
    exit 1
fi
