#!/usr/bin/env bash
# Transfers a file from this client machine to a server.
# Accepts 4 parameters
#   1- The path to the file to be transferred
#   2- The IP of the server we want to transfer the file to
#   3- The username scp connects with
#   4- The path to the SSH private key that scp uses

if [ "$#" -lt 3 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

FILE="$1"
IP="$2"
USER="$3"
SSH_KEY="$4"

scp -o "StrictHostKeyChecking = no" -i "$SSH_KEY" "$FILE" "$USER"@"$IP":~/
