#!/usr/bin/env bash
# Installs nginx web server and configures it

sudo apt-get update -y
sudo apt-get install nginx -y

# Give user ownership to websites files for accessible editing
sudo chown -R "$USER":"$USER" /var/www/html

echo "Hello World!" > /var/www/html/index.html

sudo service nginx restart
