#!/usr/bin/env bash
# Configure my Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update -y
sudo apt-get install nginx -y


echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/null
RULE="\\\n\tlocation = /redirect_me {\n\t\t return 301 https://https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"

sudo cp /etc/ginx/sites-available/default /etc/nginx/sites-available/default.bakup

sudo sed -i "53i $RULE" /etc/nginx/sites-available/default
sudo service nginx restart
