#!/usr/bin/env bash
# Displays 'Best School' 10 times, but on the 9th time, displays 'Hi' as well

(( count = 1 ))
while [ $count -le 10 ]
do
	echo "Best School"
	if [ $count == 9 ]
	then
		echo "Hi"
	fi
	((count++))
done
