#!/usr/bin/env bash
# This script displays "Best School" 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

x=0
while (( x < 10))
do
    echo "Best School"

    (( x++ ))
    
    if [ $x -eq 9 ]
    then
    	echo "Hi"
    fi
done
