#!/usr/bin/env bash
# Fixes this container so that nginx runs as the nginx user

sudo adduser --system --group nginx
sudo chown -R nginx:nginx /var/www/html
sudo chmod -R 755 /var/www/html

sudo cp -n /etc/nginx/nginx.conf /etc/nginx/nginx.conf.orig
sudo sed -i "1i\ \nuser nginx;" /etc/nginx/nginx.conf
sudo sed -i "s%80 default_server%8080 default_server%" /etc/nginx/sites-available/default 

sudo service nginx restart
