#!/usr/bin/env bash
# Fixes this container so that nginx runs as the nginx user
pkill apache2
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
