#!/usr/bin/env bash
# Creates a RSA key pair, with the private key name 'school'
# The Created key is created with 4096 bits and
# is protected by the passphrase 'betty'.
ssh-keygen -f school -b 4096 -N betty
